server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#############################新增网关配置###############################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #id：我们自定义的路由 ID，保持唯一
        ##uri：目标服务地址
        ##predicates：路由条件，Predicate接受一个输入参数返回一个布尔值。
        ##            该属性包含多种默认方法来将Predicate组合成其他复杂的逻辑(比如：与，或，非)
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          #需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
          #lb://serviceName是spring cloud gateway在微服务中自动为我们创建的负载均衡uri
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由

        - id: after_route
          uri: http://news.baidu.com #匹配后提供服务的路由地址
          predicates:
            - Path=/sports/**        # 断言，路径相匹配的进行路由
            - After=2022-09-02T11:13:03.766+08:00[Asia/Shanghai] # 这个时间后才能起效
            - Cookie=key, value   #Cookie Route Predicate需要两个参数，一个是 Cookie name ,一个是正则表达式。
                                  #路由规则会通过获取对应的 Cookie name 值和正则表达式去匹配，如果匹配上就会执行路由，如果没有匹配上则不执行

#####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka